part of '../levit_monitor.dart';

/// Function signature for sensitive data obfuscation.
typedef LevitObfuscator = String Function(dynamic value);

/// The authoritative entry point for application monitoring and diagnostics.
///
/// [LevitMonitor] acts as a unified hub that collects events from both the
/// dependency injection system and the reactive state engine. It processes
/// these events through a filtering pipeline and dispatches them to a
/// [LevitTransport] for inspection or storage.
class LevitMonitor {
  static LevitMonitorMiddleware? _middleware;

  /// The active predicate used to filter outgoing events.
  static bool Function(MonitorEvent event)? _filter;

  /// The active obfuscator used for sensitive data.
  static LevitObfuscator _obfuscator = (value) => '***';

  /// Returns the current event filter, if any.
  static bool Function(MonitorEvent event)? get filter => _filter;

  /// Configures a global filter to selectively process monitor events.
  ///
  /// The [filter] function receives every [MonitorEvent] generated by the
  /// system. Returning `true` allows the event to proceed to the transport.
  ///
  /// ### Examples
  /// ```dart
  /// // Exclude specific reactive variables by name
  /// LevitMonitor.setFilter((e) => e is! ReactiveEvent || e.reactive.name != 'secret');
  ///
  /// // Only monitor Dependency Injection events
  /// LevitMonitor.setFilter((e) => e is DependencyEvent);
  /// ```
  static void setFilter(bool Function(MonitorEvent event)? filter) {
    _filter = filter;
  }

  /// Configures a global obfuscator for sensitive data.
  static void setObfuscator(LevitObfuscator? obfuscator) {
    _obfuscator = obfuscator ?? (value) => '***';
  }

  /// Obfuscates a [value] if it is considered sensitive.
  static dynamic obfuscate(dynamic value) => _obfuscator(value);

  /// Evaluates whether a specific [event] should be processed based on the
  /// current filter configuration.
  static bool shouldProcess(MonitorEvent event) {
    return _filter == null || _filter!(event);
  }

  /// Bootstraps the monitoring system and attaches it to the application.
  ///
  /// By default, [LevitMonitor] uses a [ConsoleTransport] which pipes JSON-encoded
  /// events to standard output.
  ///
  /// *   [transport]: A single destination for monitor events.
  /// *   [transports]: A list of destinations for monitor events. If provided,
  ///     it will be combined with [transport] if both are present.
  static void attach({
    LevitTransport? transport,
    List<LevitTransport>? transports,
  }) {
    detach(); // Ensure an idempotent state

    // Monitoring relies on owner paths produced by auto-linking.
    Levit.enableAutoLinking();

    final List<LevitTransport> allTransports = [];
    if (transport != null) allTransports.add(transport);
    if (transports != null) allTransports.addAll(transports);

    final LevitTransport t;
    if (allTransports.isEmpty) {
      t = ConsoleTransport();
    } else if (allTransports.length == 1) {
      t = allTransports.first;
    } else {
      t = MultiTransport(allTransports);
    }

    _middleware = LevitMonitorMiddleware(transport: t);
    _middleware?.enable();
  }

  /// Detaches the monitor from the application and releases associated resources.
  static void detach() {
    final middleware = _middleware;
    _middleware = null;
    if (middleware == null) return;

    middleware.disable();
    unawaited(middleware.close().catchError((_) {}));
  }
}
