name: levit_monitor
description: Optional runtime telemetry, redaction, and transport pipeline for Levit applications.
repository: https://github.com/softilab/levit
version: 0.0.9
topics:
  - devtools
  - debugging
  - monitoring

environment:
  sdk: ^3.0.0

dependencies:
  # Levit Core
  levit_reactive: ^0.0.9
  levit_dart_core: ^0.0.9

  # Transports
  web_socket_channel: ^3.0.3
  
  # Annotations
  meta: ^1.17.0
  logger: ^2.6.2
  levit_scope: ^0.0.9

dev_dependencies:
  test: ^1.24.0
  lints: ^6.0.0
  rxdart: ^0.28.0
  stream_channel: ^2.1.4
